# Docker Compose Override for Local Development
# This file automatically applies when using local profile

version: '3.8'

services:
  wordpress:
    environment:
      # Override to use local MySQL instead of Azure
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wpdt
      WORDPRESS_DB_PASSWORD: wpdt123
      WORDPRESS_DB_NAME: wpdt_local_db
      
      # Remove Azure SSL configuration for local
      WORDPRESS_CONFIG_EXTRA: |
        /* Debug Configuration */
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('SAVEQUERIES', true);
        
        /* Performance Configuration */
        define('WP_POST_REVISIONS', 3);
        define('AUTOSAVE_INTERVAL', 300);
        define('WP_CRON_LOCK_TIMEOUT', 60);
        
        /* File Upload Configuration */
        ini_set('upload_max_filesize', '64M');
        ini_set('post_max_size', '64M');
        ini_set('max_execution_time', 300);
        ini_set('memory_limit', '256M');
        
        /* Security */
        define('DISALLOW_FILE_EDIT', true);
    
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./performance-monitor.php:/var/www/html/wp-content/mu-plugins/performance-monitor.php:ro
      # Remove SSL certificate volume for local development
